name: syncfusion_flutter_charts
description: Syncfusion Flutter Charts library includes data visualization widgets such as cartesian and circular charts, to create real-time, interactive, high-performance, animated charts.
version: 19.1.54
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_charts

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  vector_math: ^2.1.0
  syncfusion_flutter_core:
    path: ../syncfusion_flutter_core

flutter:
